import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]
[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
option_as_alt = "Both"
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.8
blur = true
# opacity = 1
# blur = false

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 16

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "F", mods = "Control|Shift", action = "ToggleFullscreen" },
  { key = "M", mods = "Control|Shift", action = "ToggleMaximized" },
  { key= "Q", mods= "Control|Shift", action= "Quit" },
  { key= "H", mods= "Control|Shift", action= "Hide" },
]

[mouse]
hide_when_typing = true
